#!/usr/bin/env python
"""Write the fully resolved configs in this directory. Rerunning it must reproduce them byte for byte.

Every key eval/text_rebase.py reads is written out here, so the JSONs depend on nothing
but this file: no base config, no override resolution. One file per (cell, seed), so a
run is a single plain command, from the repository root:

    python -m merge_and_rebase.eval.text_rebase --config <file> --local-log-dir results/block_ridge_ntk_attention/<task>/<stem> --run-name summary

Each config has its own feature cache, results/block_ridge_ntk_attention/<task>/<stem>/feature_cache/
(relative to the repository root, git-ignored): a job never reads or writes another job's
features, so jobs can run in any order or concurrently, and rerunning a config reuses its
own cache. A cold cache costs a few minutes on one GPU (A's per-block jvps, then B's blocks).

Usage:
    python configs/block_ridge_ntk_attention/make_configs.py            # (re)write all
    python configs/block_ridge_ntk_attention/make_configs.py --check    # fail if any file differs
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WORK = "/work/intesasanpaolo_phd/merge-and-rebase"

TASKS = ("snli",)
SEEDS = (33, 54, 89)
FEW_SHOT = 1000  # the largest support of the original grid (groups *-fs1000): 1000 per class

# Shared by every cell. Values are those of configs/text_rebase_t5enc_steer.json with the
# grid's noreg-ntk:linear overrides (scripts/slurm/grid.py: overrides_for), except
# eval_source_finetuned, which is off: that control evaluates A's ntk checkpoint through a
# *nonlinear* forward, where it is known to score near chance, and it does not affect the
# steer_text result.
COMMON = {
    "suite": "nli6",
    "source_model_name_or_path": "google-t5/t5-base",
    "source_model_arch": "t5",
    "target_model_name_or_path": "google-t5/t5-large",
    "target_model_arch": "t5",
    "model_kind": "encoder_classification",
    "num_labels": 3,
    "device": "cuda",
    "dtype": "fp32",
    "eval_mode": "head_logits",
    "head_key_pattern": "classification_head",
    "split": "test",
    "val_fraction": 0.1,
    "max_samples_per_task": 2000,
    "max_train_samples": 4000,
    "batch_size": 16,
    "num_workers": 0,
    "max_length": 256,
    "method": "steer_text",
    "alpha_search": False,
    "alpha": 1.0,
    "alpha_selection": "shared",
    "weights": None,
    "strict_load": False,
    "eval_source_finetuned": False,
    "save_steer_artifacts_dir": None,
}

RESULTS = "results/block_ridge_ntk_attention"  # relative to the repository root

COMMON_METHOD = {
    "feature_regime": "linear",
    "few_shot": FEW_SHOT,
    "stage1_lambda": 1.0,
    "force_recompute_features": False,
}

BLOCK_RIDGE_TRACE_CARRY = {
    "stage_2_strategy": "block_ridge",
    "block_ridge_lambda_scaling": "trace",
    "block_ridge_mode": "smoothed_residual",
    "rho": 1.0,
    "block_group_strategy": "concat",
    "block_ridge_target_strategy": "reuse_logitmap",
    "block_residuals_weighting_strategy": "identity",
    "block_pooling": "mean",
    "block_feature_preprocessing": "none",
}

# ridge_lambda: the value picked on held-out rows (label-free, logit R^2) by the offline
# refit, scripts/block_ridge_experiments/preprocess_curve.py; see the README.
CELLS = {
    # The method: block_ridge, trace-scaled lambda, smoothed-residual carry, on B's
    # attention outputs (input of SelfAttention.o). Offline beta = 0.1 at n = 1500 and 3400.
    "attention_block_ridge_trace_carry": {**BLOCK_RIDGE_TRACE_CARRY, "block_source": "attention", "ridge_lambda": 0.1},
    # Reference: the same fit on B's residual stream (the cached block features).
    # Offline beta = 0.1 at n = 1500, 1e-4 at n = 3400; the support here is 3000 rows.
    "residual_block_ridge_trace_carry": {**BLOCK_RIDGE_TRACE_CARRY, "block_source": "residual", "ridge_lambda": 1e-4},
    # Reference: global ridge on f_B. Offline beta = 0.1 relative to mean ||f_B||^2 = 6.25.
    "global_ridge": {"stage_2_strategy": "global_ridge", "ridge_lambda": 0.625},
}


def head_file(task: str) -> str:
    return f"{WORK}/text_rebase_heads/t5-large_{task}_nearest_mean_enc_seed33_fewshot300.pt"


def stem(task: str, cell: str, seed: int) -> str:
    return f"{task}_{cell}_fs{FEW_SHOT}_seed{seed}"


def config(task: str, cell: str, seed: int) -> dict:
    cfg = copy.deepcopy(COMMON)
    cfg.update(
        {
            "_description": (
                f"steer_text {cell} on {task}, few_shot={FEW_SHOT}, seed={seed}. Generated by "
                "configs/block_ridge_ntk_attention/make_configs.py; see the README there."
            ),
            "tasks": task,
            "seed": seed,
            "tuned_ckpts": {task: f"{WORK}/checkpoints_t5_converted/t5base_6text_noreg_ntk/{task}"},
            "target_task_heads": head_file(task),
            "method_params": {
                **COMMON_METHOD,
                "feature_cache_dir": f"{RESULTS}/{task}/{stem(task, cell, seed)}/feature_cache/",
                **CELLS[cell],
            },
        }
    )
    return cfg


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if any file differs from what would be written")
    args = parser.parse_args()
    stale = []
    for task in TASKS:
        out_dir = HERE / task
        out_dir.mkdir(exist_ok=True)
        for cell in CELLS:
            for seed in SEEDS:
                path = out_dir / f"{stem(task, cell, seed)}.json"
                text = json.dumps(config(task, cell, seed), indent=2) + "\n"
                if args.check:
                    if not path.exists() or path.read_text() != text:
                        stale.append(path)
                else:
                    path.write_text(text)
                    print(f"wrote {path.relative_to(HERE.parents[1])}")
    if stale:
        print("differs from make_configs.py:", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
